services:

  backend:
    build: ./backend
    container_name: network-backend
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16
    container_name: network-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: network_monitor

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana
    container_name: network-grafana

    ports:
      - "3001:3000"

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus
    container_name: network-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - backend

volumes:
  postgres_data:
  grafana_data:
